---
- name: Converge
  hosts: all
  become: yes
  gather_facts: true
  vars:
    zsh_sources_extras:
      - { name: 'Wal Colors', path: '$HOME/.cache/wal/colors.sh'}
    zsh_export_vars_extras:
      - { name: 'Default editor', variable: 'EDITOR', value: 'nvim'}
    zsh_paths_extras:
      - { name: 'Lua language server', path: '/usr/bin/lua-language-server'}



  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
    
    - name: Run the equivalent of "pacman -Syu" as a separate step
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == 'Archlinux'

    - name: upgrade all packages
      yum: 
        name: '*' 
        state: latest 
        update_cache: yes
      when: ansible_os_family == 'CentOS'

  roles:
    - role: 'quantumfate.zsh'
      

