---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: geerlingguy instances
    image: "geerlingguy/docker-${MOLECULE_DISTRO_GEERLINGGUY}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true

  # - name: other instances
  #   image: "artis3n/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   privileged: true
  #   pre_build_image: true
  
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        zsh_user: root
        zsh_mc_solarized_skin: yes
        zsh_antigen_bundles_extras:
          - { name: test/in-list, when: true }
          - { name: test/not-in-list, when: false }
          - { name: test/command-exists, command: zsh }
          - { name: test/command-not-exists, command: not-exists-commanddd }

verifier:
  name: ansible
