---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: geerlingguy
    image: "geerlingguy/docker-${MOLECULE_DISTRO_GEERLINGGUY:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

  - name: other
    image: "artis3n/docker-${MOLECULE_DISTRO_ALT:-arch}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
  
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        zsh_user: root
        zsh_mc_solarized_skin: yes
        zsh_antigen_bundles_extras:
          - { name: test/in-list, when: true }
          - { name: test/not-in-list, when: false }
          - { name: test/command-exists, command: zsh }
          - { name: test/command-not-exists, command: not-exists-commanddd }

verifier:
  name: ansible
